import numpy as np
from sklearn import datasets
from sklearn.utils import shuffle
bunch = datasets.load_boston()
X, y = shuffle(bunch.data, bunch.target)
print("X.shape: ",X.shape)
print("y.shape: ",y.shape)
print("bunch.data.shape: ",bunch.data.shape)
print("bunch.target.shape: ",bunch.target.shape)
# print("X: ",X)
# print("y: ",y)
X, y = shuffle(bunch.data, bunch.target,random_state=0)
print("X.shape: ",X.shape)
print("y.shape: ",y.shape)
print("bunch.data.shape: ",bunch.data.shape)
print("bunch.target.shape: ",bunch.target.shape)
# print("X: ",X)
# print("y: ",y)
X, y = shuffle(X, y,random_state=0)
# print("X: ",X)
# print("y: ",y)
X, y = shuffle(X, y,random_state=0)
# print("X: ",X)
# print("y: ",y)
# my_xx = np.empty([512,50,90],float)
#my_xx = np.empty([0,50,90],float)
my_xx = np.random.rand(0,50,90)
# my_yy = np.empty([13782,8],float)
#my_yy = np.empty([1,8],float)
my_yy = np.random.rand(1,8)
print("my_xx.shape: ",my_xx.shape)
print("my_xx: ",my_xx)
print("my_yy.shape: ",my_yy.shape)
print("my_yy: ",my_yy)
#my_xx, my_yy = shuffle(my_xx,my_yy,random_state=0)
my_xx = np.expand_dims(my_xx,axis=0)
my_yy = np.expand_dims(my_yy,axis=0)
my_xx, my_yy = shuffle(my_xx,my_yy,random_state=0)
print("my_xx.shape: ",my_xx.shape)
print("my_xx: ",my_xx)
print("my_yy.shape: ",my_yy.shape)
print("my_yy: ",my_yy)
# my_xx = my_xx.reshape(0,my_xx)
# my_yy = my_yy.reshape(0,my_yy)
my_xx, my_yy = shuffle(my_xx,my_yy,random_state=0)
